 ## Cleaning Program 
 ### Author: Kyle Sprague 
 ### Date: 09/01/2022 

The purpose of the program is to clean a business travel spreadsheet by removing lines where origin nd destination are the same and second lines when two lines are duplicates. In addition, lines where the transaction amount is less than \\$50.00 are removed. This program contains the function "cleaning", the details of which are provided below.

In [1]:
#importing relevant libraries 
import pandas as pd 
import numpy as np  
#adjusting the display function such that it displays the entire data frame:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
#pd.set_option('display.width', None)
#pd.set_option('display.max_colwidth', None)

In [63]:
#reading the travel file and airport codes into the notebook 
travel_df = pd.read_excel("JPM Airline Activity 7.1.2020 - 6.30.21 for Tom.xlsx") 
airport_codes_df = pd.read_csv("airport_codes.csv")  
bates_business_df = pd.read_excel("bates_business_travel_locations.xls",sheet_name='Staff')
display(bates_business_df)
origins_df, dest_df = pd.DataFrame(), pd.DataFrame() 
origins_df["Origination"] = travel_df["Origination"] 
dest_df["Destination"] = travel_df["Destination"]

,Last Name,First Name,Account Number,Traveler Name,Unnamed: 4,Departure Date,Transaction Date,Origination,Destination,Ticket Number,Referenced Transaction Amount,Transaction Amount
0,BARNES,MCKELL J,************8048,BARNES/MCKELL,Staff,2021-06-16 09:59:00,2021-06-02,BOS,PHL,2797564089546,98.40,98.40
1,BARNES,MCKELL J,************8048,BARNES/MCKELL MS,NaN,2021-07-13 00:00:00,2021-06-16,BUR,JFK,2792167214387,343.20,343.20
2,BARNES,MCKELL J,************8048,BARNES/MCKELL MS,NaN,2021-07-13 00:00:00,2021-06-16,JFK,BOS,2792167214387,343.20,NaN
3,DAVIS JR.,KEITH,************3025,DAVIS JR/KEITH,Staff,2021-06-25 00:00:00,2021-06-20,ATL,BOS,62460278884,278.40,278.40
4,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,Staff,2021-06-04 06:30:00,2021-05-22,BOS,DFW,17561925356,216.19,216.19
5,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-04 10:41:00,2021-05-22,DFW,ONT,17561925356,216.19,NaN
6,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-11 07:00:00,2021-05-22,PHX,DFW,17561927632,284.20,284.20
7,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-11 12:51:00,2021-05-22,DFW,BNA,17561927632,284.20,NaN
8,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,Staff,2021-07-06 00:00:00,2021-06-24,PDX,IAD,162354801647,871.40,871.40
9,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,IAD,PWM,162354801647,871.40,NaN
10,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,PWM,EWR,162354801647,871.40,NaN
11,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,EWR,PDX,162354801647,871.40,NaN
12,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF,Staff,2021-06-25 00:00:00,2021-06-04,PWM,IAD,162351393130,297.20,297.20
13,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF,NaN,2021-06-25 00:00:00,2021-06-04,IAD,PDX,162351393130,297.20,NaN
14,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF MR,NaN,2021-07-02 00:00:00,2021-06-03,PDX,JFK,2792166283760,398.20,398.20
15,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF MR,NaN,2021-07-02 00:00:00,2021-06-03,JFK,PWM,2792166283760,398.20,NaN
16,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,Guest Lecturer,2021-06-13 06:00:00,2021-06-02,BNA,ATL,67542014713,390.40,390.40
17,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-13 11:15:00,2021-06-02,ATL,PWM,67542014713,390.40,NaN
18,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-16 07:15:00,2021-06-02,PWM,LGA,67542014713,390.40,NaN
19,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-16 11:40:00,2021-06-02,LGA,BNA,67542014713,390.40,NaN
20,FEIN,JASON S,************5461,JASON FEIN,Falculty,2021-10-02 00:00:00,2021-06-13,PWM,DCA,12181067843,214.90,214.90
21,FEIN,JASON S,************5461,JASON FEIN,NaN,2021-10-02 00:00:00,2021-06-13,DCA,MSY,12181067843,214.90,NaN
22,FEIN,JASON S,************5461,JASON FEIN,NaN,2021-10-02 00:00:00,2021-06-13,MSY,CLT,12181067843,214.90,NaN
23,MARTIN,JONATHAN D,************2422,JONATHAN MARTIN,Staff,2021-06-25 00:00:00,2021-06-14,SNA,DFW,12181330753,343.20,343.20
24,MARTIN,JONATHAN D,************2422,JONATHAN MARTIN,NaN,2021-06-25 00:00:00,2021-06-14,DFW,BOS,12181330753,343.20,NaN
25,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,Staff,2021-06-12 00:00:00,2021-05-26,BOS,ORD,62455117954,291.60,291.60
26,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-12 00:00:00,2021-05-26,ORD,DTW,62455117954,291.60,NaN
27,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-12 00:00:00,2021-05-26,DTW,BOS,62455117954,291.60,NaN
28,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-22 00:00:00,2021-06-11,BOS,ORD,12180752170,236.20,236.20
29,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-22 00:00:00,2021-06-11,ORD,SNA,12180752170,236.20,NaN
30,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-28 00:00:00,2021-06-18,BOS,RIC,62459691493,258.40,258.40
31,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-07-14 00:00:00,2021-06-21,BOS,LAX,62460566444,219.40,219.40
32,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN DAVI,Staff,2021-07-05 00:00:00,2021-06-20,BOS,DFW,2792167522937,480.79,480.79
33,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN DAVI,NaN,2021-07-05 00:00:00,2021-06-20,DFW,BOS,2792167522937,480.79,NaN
34,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAND,Staff,2021-07-16 00:00:00,2021-06-28,LAX,BOS,162355310452,339.40,339.40
35,BARNES,MCKELL J,************8048,MCKELL BARNES,Staff,2021-06-19 00:00:00,2021-06-02,PHL,BOS,12178568403,98.40,98.40
36,BARNES,MCKELL J,************8048,MCKELL BARNES,NaN,2021-07-11 00:00:00,2021-06-16,ATL,DFW,12181900641,298.20,298.20
37,BARNES,MCKELL J,************8048,MCKELL BARNES,NaN,2021-07-11 00:00:00,2021-06-16,DFW,BUR,12181900641,298.20,NaN
38,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-25 07:15:00,2021-05-22,ATL,BOS,67561927732,168.40,168.40
39,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-04 06:30:00,2021-05-22,BOS,DFW,17561925355,216.19,216.19
40,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-04 10:41:00,2021-05-22,DFW,ONT,17561925355,216.19,NaN
41,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-11 07:00:00,2021-05-22,PHX,DFW,17561927631,284.20,284.20
42,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-11 12:51:00,2021-05-22,DFW,BNA,17561927631,284.20,NaN
43,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,Staff,2020-11-24 06:05:00,2020-11-19,PWM,ORD,167522684179,302.60,302.60
44,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2020-11-24 08:50:00,2020-11-19,ORD,TUS,167522684179,302.60,NaN
45,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2021-02-16 13:12:00,2021-02-12,TUS,ATL,67542014339,359.20,359.20
46,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2021-02-16 19:55:00,2021-02-12,ATL,PWM,67542014339,359.20,NaN
47,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,Staff,2021-07-09 00:00:00,2021-05-30,SDF,MDW,5262392216215,189.98,189.98
48,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-12 00:00:00,2021-05-30,MDW,PWM,5262392216603,338.97,338.97
49,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-05 00:00:00,2021-05-30,PWM,BWI,5262392218170,428.98,428.98
50,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-05 00:00:00,2021-05-30,BWI,SDF,5262392218170,428.98,NaN
51,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,Staff,2021-05-21 08:20:00,2021-05-10,MSP,ORD,167542014627,784.40,784.40
52,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-21 11:00:00,2021-05-10,ORD,PWM,167542014627,784.40,NaN
53,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-23 07:15:00,2021-05-10,PWM,EWR,167542014627,784.40,NaN
54,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-23 10:30:00,2021-05-10,EWR,MSP,167542014627,784.40,NaN
55,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,Staff,2021-06-01 07:30:00,2021-05-27,PWM,ATL,67563023730,308.59,308.59
56,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-01 11:22:00,2021-05-27,ATL,MIA,67563023730,308.59,NaN
57,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-15 11:10:00,2021-05-27,MIA,LGA,67563023730,308.59,NaN
58,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-15 15:08:00,2021-05-27,LGA,PWM,67563023730,308.59,NaN
59,FABRIZIO,TRACY L,************0289,PIEN/LAURENH,Staff,2021-03-24 00:00:00,2021-03-16,SFO,BOS,162340092150,576.80,576.80
60,FABRIZIO,TRACY L,************0289,PIEN/LAURENH,NaN,2021-03-24 00:00:00,2021-03-16,BOS,SFO,162340092150,576.80,NaN
61,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,BOS,KEF,762705728,2706.85,2706.85
62,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,KEF,OSL,762705728,2706.85,NaN
63,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,OSL,KEF,762705728,2706.85,NaN
64,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,KEF,BOS,762705728,2706.85,NaN
65,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,Falculty,2021-07-07 09:55:00,2021-05-28,OSL,LYR,1177627057283,623.00,623.00
66,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,NaN,2021-09-05 14:50:00,2021-05-28,LYR,TOS,1177627057283,623.00,NaN
67,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,NaN,2021-09-05 17:30:00,2021-05-28,TOS,OSL,1177627057283,623.00,NaN

In [64]:
def cleaning(travel_df, origins_df, dest_df):
    ''' 
        The purpose of this function is to perform three cleaning operations given a travel data file  
        inputed as a data frame.  
        
        Inputs:  
            travel_df: a data frame containing the travel file information in its entirity 
            origins_df: a data frame with just the origination column of the travel file 
            dest_df: a data frame containing just the destination column of the travel file 
    
        Returns:  
            an updated data frame with redundant and false data redacted 
    '''
    travel_copy = travel_df.copy()
    travel_df["Comparison"] = travel_df["Origination"] == travel_df["Destination"]  
    #creating a new column in the travel data frame  with just the origin with true/False 
    #depending on where the origination entry in each row is equal to the destination entry in 
    #the same row 
    
    if (travel_df["Referenced Transaction Amount"] <= 50.00).any(): 
        #checks if any row in the "Referenced Transaction Amount Column" is less than fifty
        fake_flight_row = (travel_df[travel_df["Referenced Transaction Amount"] <= 50.00].index.values) 
        #fake_flight_row represents the index of the row where "Referenced Transaction Amount" 
        #is less than 50 
        travel_copy = travel_copy.drop(fake_flight_row) 

    elif travel_copy["Comparison"].any() == True: #if any value in the comparison column is true 
        orig_eq_dest_row = (travel_copy[travel_copy["Origination"] == travel_copy["Destination"]].index.values)  
        #orig_eq_dest_row represents the row in the travel file copy where the Origin and Destination 
        #are the same for a row 
        travel_copy = (travel_copy.drop(orig_eq_dest_row, axis = 0)) 

    travel_copy = travel_copy.drop_duplicates(subset = ['Origination', 'Destination', 'Ticket Number'])  
    #drop the second row (in terms of appearance) where the origination, destination, and ticket number 
    #are the smame 
    return travel_copy

In [67]:
travel_df_cleaned = cleaning(travel_df, origins_df, dest_df)  
travel_df_cleaned.to_csv("Cleaned_Travel_File.csv")

68

,Last Name,First Name,Account Number,Traveler Name,Unnamed: 4,Departure Date,Transaction Date,Origination,Destination,Ticket Number,Referenced Transaction Amount,Transaction Amount,Comparison
0,BARNES,MCKELL J,************8048,BARNES/MCKELL,Staff,2021-06-16 09:59:00,2021-06-02,BOS,PHL,2797564089546,98.40,98.40,False
2,BARNES,MCKELL J,************8048,BARNES/MCKELL MS,NaN,2021-07-13 00:00:00,2021-06-16,BUR,JFK,2792167214387,343.20,343.20,False
3,BARNES,MCKELL J,************8048,BARNES/MCKELL MS,NaN,2021-07-13 00:00:00,2021-06-16,JFK,BOS,2792167214387,343.20,NaN,False
4,DAVIS JR.,KEITH,************3025,DAVIS JR/KEITH,Staff,2021-06-25 00:00:00,2021-06-20,ATL,BOS,62460278884,278.40,278.40,False
5,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,Staff,2021-06-04 06:30:00,2021-05-22,BOS,DFW,17561925356,216.19,216.19,False
6,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-04 10:41:00,2021-05-22,DFW,ONT,17561925356,216.19,NaN,False
8,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-11 07:00:00,2021-05-22,PHX,DFW,17561927632,284.20,284.20,False
9,MCLAUGHLIN,GARRETT,************4481,DAVIS/KEITH,NaN,2021-06-11 12:51:00,2021-05-22,DFW,BNA,17561927632,284.20,NaN,False
19,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,Staff,2021-07-06 00:00:00,2021-06-24,PDX,IAD,162354801647,871.40,871.40,False
20,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,IAD,PWM,162354801647,871.40,NaN,False
21,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,PWM,EWR,162354801647,871.40,NaN,False
22,FABRIZIO,TRACY L,************0289,HAYES/EMILYJOANNE,NaN,2021-07-06 00:00:00,2021-06-24,EWR,PDX,162354801647,871.40,NaN,False
26,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF,Staff,2021-06-25 00:00:00,2021-06-04,PWM,IAD,162351393130,297.20,297.20,False
27,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF,NaN,2021-06-25 00:00:00,2021-06-04,IAD,PDX,162351393130,297.20,NaN,False
28,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF MR,NaN,2021-07-02 00:00:00,2021-06-03,PDX,JFK,2792166283760,398.20,398.20,False
29,HERGETH,RUDOLF,************3260,HERGETH/RUDOLF MR,NaN,2021-07-02 00:00:00,2021-06-03,JFK,PWM,2792166283760,398.20,NaN,False
30,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,Guest Lecturer,2021-06-13 06:00:00,2021-06-02,BNA,ATL,67542014713,390.40,390.40,False
31,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-13 11:15:00,2021-06-02,ATL,PWM,67542014713,390.40,NaN,False
32,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-16 07:15:00,2021-06-02,PWM,LGA,67542014713,390.40,NaN,False
33,WALSH,STEPHANIE L,************4933,ISAAC/WALTER RICHARD,NaN,2021-06-16 11:40:00,2021-06-02,LGA,BNA,67542014713,390.40,NaN,False
35,FEIN,JASON S,************5461,JASON FEIN,Falculty,2021-10-02 00:00:00,2021-06-13,PWM,DCA,12181067843,214.90,214.90,False
36,FEIN,JASON S,************5461,JASON FEIN,NaN,2021-10-02 00:00:00,2021-06-13,DCA,MSY,12181067843,214.90,NaN,False
37,FEIN,JASON S,************5461,JASON FEIN,NaN,2021-10-02 00:00:00,2021-06-13,MSY,CLT,12181067843,214.90,NaN,False
38,MARTIN,JONATHAN D,************2422,JONATHAN MARTIN,Staff,2021-06-25 00:00:00,2021-06-14,SNA,DFW,12181330753,343.20,343.20,False
39,MARTIN,JONATHAN D,************2422,JONATHAN MARTIN,NaN,2021-06-25 00:00:00,2021-06-14,DFW,BOS,12181330753,343.20,NaN,False
40,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,Staff,2021-06-12 00:00:00,2021-05-26,BOS,ORD,62455117954,291.60,291.60,False
41,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-12 00:00:00,2021-05-26,ORD,DTW,62455117954,291.60,NaN,False
42,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-12 00:00:00,2021-05-26,DTW,BOS,62455117954,291.60,NaN,False
43,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-22 00:00:00,2021-06-11,BOS,ORD,12180752170,236.20,236.20,False
44,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-22 00:00:00,2021-06-11,ORD,SNA,12180752170,236.20,NaN,False
46,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-06-28 00:00:00,2021-06-18,BOS,RIC,62459691493,258.40,258.40,False
47,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN,NaN,2021-07-14 00:00:00,2021-06-21,BOS,LAX,62460566444,219.40,219.40,False
48,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN DAVI,Staff,2021-07-05 00:00:00,2021-06-20,BOS,DFW,2792167522937,480.79,480.79,False
49,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAN DAVI,NaN,2021-07-05 00:00:00,2021-06-20,DFW,BOS,2792167522937,480.79,NaN,False
50,MARTIN,JONATHAN D,************2422,MARTIN/JONATHAND,Staff,2021-07-16 00:00:00,2021-06-28,LAX,BOS,162355310452,339.40,339.40,False
51,BARNES,MCKELL J,************8048,MCKELL BARNES,Staff,2021-06-19 00:00:00,2021-06-02,PHL,BOS,12178568403,98.40,98.40,False
52,BARNES,MCKELL J,************8048,MCKELL BARNES,NaN,2021-07-11 00:00:00,2021-06-16,ATL,DFW,12181900641,298.20,298.20,False
53,BARNES,MCKELL J,************8048,MCKELL BARNES,NaN,2021-07-11 00:00:00,2021-06-16,DFW,BUR,12181900641,298.20,NaN,False
56,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-25 07:15:00,2021-05-22,ATL,BOS,67561927732,168.40,168.40,False
58,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-04 06:30:00,2021-05-22,BOS,DFW,17561925355,216.19,216.19,False
59,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-04 10:41:00,2021-05-22,DFW,ONT,17561925355,216.19,NaN,False
61,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-11 07:00:00,2021-05-22,PHX,DFW,17561927631,284.20,284.20,False
62,MCLAUGHLIN,GARRETT,************4481,MCLAUGHLIN/GARRETT E,NaN,2021-06-11 12:51:00,2021-05-22,DFW,BNA,17561927631,284.20,NaN,False
66,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,Staff,2020-11-24 06:05:00,2020-11-19,PWM,ORD,167522684179,302.60,302.60,False
67,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2020-11-24 08:50:00,2020-11-19,ORD,TUS,167522684179,302.60,NaN,False
69,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2021-02-16 13:12:00,2021-02-12,TUS,ATL,67542014339,359.20,359.20,False
70,WALSH,STEPHANIE L,************4933,MOHAMED/AMINA KHADIR,NaN,2021-02-16 19:55:00,2021-02-12,ATL,PWM,67542014339,359.20,NaN,False
72,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,Staff,2021-07-09 00:00:00,2021-05-30,SDF,MDW,5262392216215,189.98,189.98,False
73,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-12 00:00:00,2021-05-30,MDW,PWM,5262392216603,338.97,338.97,False
74,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-05 00:00:00,2021-05-30,PWM,BWI,5262392218170,428.98,428.98,False
75,MONTGOMERY,ALISON K,************9130,MONTGOMERY/ALISON K,NaN,2021-07-05 00:00:00,2021-05-30,BWI,SDF,5262392218170,428.98,NaN,False
76,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,Staff,2021-05-21 08:20:00,2021-05-10,MSP,ORD,167542014627,784.40,784.40,False
77,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-21 11:00:00,2021-05-10,ORD,PWM,167542014627,784.40,NaN,False
78,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-23 07:15:00,2021-05-10,PWM,EWR,167542014627,784.40,NaN,False
79,WALSH,STEPHANIE L,************4933,MORRISSEY/ALEC CHARL,NaN,2021-05-23 10:30:00,2021-05-10,EWR,MSP,167542014627,784.40,NaN,False
81,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,Staff,2021-06-01 07:30:00,2021-05-27,PWM,ATL,67563023730,308.59,308.59,False
82,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-01 11:22:00,2021-05-27,ATL,MIA,67563023730,308.59,NaN,False
83,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-15 11:10:00,2021-05-27,MIA,LGA,67563023730,308.59,NaN,False
84,PATTERSON,CUSTAVIOUS V,************1240,PATTERSON/CUSTAVIOUS,NaN,2021-06-15 15:08:00,2021-05-27,LGA,PWM,67563023730,308.59,NaN,False
87,FABRIZIO,TRACY L,************0289,PIEN/LAURENH,Staff,2021-03-24 00:00:00,2021-03-16,SFO,BOS,162340092150,576.80,576.80,False
88,FABRIZIO,TRACY L,************0289,PIEN/LAURENH,NaN,2021-03-24 00:00:00,2021-03-16,BOS,SFO,162340092150,576.80,NaN,False
90,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,BOS,KEF,762705728,2706.85,2706.85,False
91,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,KEF,OSL,762705728,2706.85,NaN,False
92,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,OSL,KEF,762705728,2706.85,NaN,False
93,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL,NaN,NaT,2021-05-30,KEF,BOS,762705728,2706.85,NaN,False
94,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,Falculty,2021-07-07 09:55:00,2021-05-28,OSL,LYR,1177627057283,623.00,623.00,False
95,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,NaN,2021-09-05 14:50:00,2021-05-28,LYR,TOS,1177627057283,623.00,NaN,False
96,RETELLE,MICHAEL J,************3229,RETELLE/MICHAEL JAME,NaN,2021-09-05 17:30:00,2021-05-28,TOS,OSL,1177627057283,623.00,NaN,False